name: Lesson 2

on:
  push:
    branches:
      - lesson-2
jobs:
  build_and_test:
    runs-on: ubuntu-latest
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Disable Debug
        run: |
          sed -i 's/DEBUG = True/DEBUG = False/g' hangry_api/hangry_api/settings.py
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk'
        run: echo Placeholder for Deployment
      - uses: actions/checkout@v4 
      - name: install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install pytest django_mock_queries six coverage
        working-directroy: backend
      - name: Run unit tests
        run: |
          coverage run -m --source=./hangry_api pytest
          coverage report
        working-directory: backend